### PR TITLE
Create config_tool.html

### PR DESCRIPTION
**Pull request by mfo13**
It's an attempt of an "easy" to use configuration tool for AnimCubeJS.

### CODE REVIEW

**Comment by mfeather1** [comment]
Nice!  
There is a problem, it needs global var removeListeners: 
    <script>
    var removeListeners = [];    <-- Add (prior to first call to AnimCube)
    AnimCube3("id=cube");

In function replace_cube() it needs the following line prior to any subsequent calls to AnimCube (prior to the switch statement):
```removeListeners['cube']();```

**Comment by mfo13** [comment]
OK! I did that but I don't know why... can you tell me?

**Comment by mfeather1** [comment]
It was locking me out of entering any parameters after making the first change.  Each time AnimCube is called new listeners are created, the old ones need to be removed to avoid problems like that.  There's more about it in the doc in the section: "Show how to use AnimCubeJS with JavaScript".

I linked the config tool in the doc right after the part about "declaring  parameters online", the direct link is:
https://mfeather1.github.io/test/AnimCubeJS-gh-pages/sources/codes/enhancement/parameters/config_tool.html

**Comment by mfo13** [comment]
Oh, Nice! That's why it was freezing in my cell phone! Actually I was thinking about flushing the DOM somehow but I could not remember this technical detail from the doc. By the way, the new version of the doc looks very fine! I think it would be also useful generating a kind of programmer's doc, at least showing the algorithm logic (strategy) and how it handles with many fundamental aspects, like slicing the cube, rotating the observer instead of the cube, layer drawing order, etc., etc. Perhaps a section for each important function inside AnimCubeJS.

**Comment by mfeather1** [comment]
I think a prerequisite for documenting the 3D aspects of AnimCube is a course in Linear Algebra, so I'm exempt. :)

**Comment by mfo13** [comment]
Facelets easy pick tool now integrated. The code got a bit messy but seems to work. It needs simplification, clearness and more efficiency (many useless repetitions). A working demo can be found in: https://mfo13.github.io/

**Comment by mfeather1** [comment]
Outstanding!  I copied it to https://mfeather1.github.io/test/AnimCubeJS-gh-pages/config_tool.html.  I was just thinking that if you want to host it on your site I could change the link in the AnimCube Doc to go to your site.

I went off on a tangent because I got the idea to have direct access to the facelets array in AnimCube and then I got the idea that it could be modified to automatically link any var in the web page prefixed with "acjs_" to the actual var in the  program with the same name (so for example acjs_cube in the web page links directly to the cube array in AnimCube).  Then I  made a doc page showing how to use it and now I'm in the process of changing the removeListeners links to acjs_removeListeners in the programs in the enhanced section to be consistent.  So I hope to get all these changes moved to my test repo this week and then get the AnimCubeJS repo updated next week.

**Comment by mfo13** [comment]
Thank you! However I think there is no need of linking to my site, since it is not actually a site, it is just for testing and learning porposes. By the way, AnimCubeJS has already its own site. So, since you have accepted this branch it can be acessed by other interested people if they find the config_tool useful and they can also contribute to make it better. I think your idea of linking the internal AnimCubeJS variables to the html DOM environment is very nice! So we can have two levels of webpages programming. The usual "command line" way, for rapid setups and more simple applications and this new more deep approach if someone wants more complex applications. When you implement that I'll try to simplify the config tool. I'm still working on the colorscheme and superfacelets easy picking.

**Comment by mfo13** [comment]
Integrated 3 more easy-tools: position, colorscheme and superfacelets. I think now it is done, the first version as I've planned in my mind. You can test the demo at https://mfo13.github.io/

**Comment by mfeather1** [comment]
Looks good to me, only thing is that I had to take out "scripts/" from:
<script src="scripts/AnimCube2.js"></script>
...
<script src="scripts/AnimCube7.js"></script>

Everything is set up in my test repo the way I intend to install into the AnimCubeJS repo next week:
https://mfeather1.github.io/test/AnimCubeJS-gh-pages/animcubejs.html

The documentation for direct access is at the bottom of the doc in a new show/hide section named: "The Direct Access Method (for Programmers)" which has several links for examples  of which my facelet_editor is one.

**Comment by mfeather1** [comment]
I found a bug in AnimCubeJS that has apparently been there since the beginning, the following will cause it to crash (it is one digit short on the last color which should be 0000ff):
colorscheme=012345&colors=ff0000FFA500ffff00ffffff00ff000000f

test here:
https://animcubejs.cubing.net/sources/codes/enhancement/parameters/create.html

I fixed the programs in the test repo so it works here:

https://mfeather1.github.io/test/AnimCubeJS-gh-pages/sources/codes/enhancement/parameters/create.html

Also, to work with the new versions of AnimCube[2-7].js removeListeners needs to be changed to acjs_removeListeners in web pages.

**Comment by mfo13** [comment]
I didn't notice that. I thought colors would not (or should not) accept less than 60 characters (10 colors) to work, as is the case with facelets. If you don't provide N*N*6 facelets it automatically sets to the default. I think it should be the same for colors. Since you are not using the default 10 numerical colors you should provide all of them. This is not an issue, actually, when you use the config tool. By the way, I made some few final touches, so the tool is ready to be published. The correct code (without the "scripts/" is found here, in this current branch we discuss (patch-1 on mfo13/AnimCubeJS), the https://mfo13.github.io/ is just for testing. (ps.: just remember to change removelisteners when you release the new AnimCubeJS versions). I'll read about the new features later.

**Comment by mfeather1** [comment]
I updated the AnimCubeJS repo with all of the recent mods, the changes are here:

https://github.com/cubing/AnimCubeJS/commit/723383ac9a685d8be234a9963c0b7dfa4f2038e8

The config tool was included in the update so I think this pull request can be closed.

**Comment by mfo13** [comment]
OK! Closed.

**Pull request closed without merging**
